news/news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('newspaper/', include('newspaper.urls')),
    path('', include('user_auth.urls')),
    path('admin/', admin.site.urls),
    path('files/', include('app_media.urls')),
    path('send_email/', include('app_logic.urls')),
]

news/newspaper/urls.py
from django import views
from django.urls import path
from newspaper import views

urlpatterns = [
    path('', views.NewsView.as_view()),
    path('create/', views.NewsCreate.as_view()),
    path('tag/<int:tag_id>/', views.NewsViewTag.as_view()),
    path('news/<int:news_id>/', views.NewsDetail.as_view()),
    path('news/<int:news_id>/add_comment/', views.CommentCreate.as_view()),
    path('news/<int:news_id>/edit/', views.NewsEdit.as_view())
]

news/newspaper/models.py
from secrets import choice
from django.db import models
# Получим таблицу пользователей (модель по умолчанию):
from django.contrib.auth.models import User

# Create your models here.


class Tags(models.Model):

    title = models.CharField(max_length=20, verbose_name='Тег', default='Другое')

    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'Новостные теги'


class Comments(models.Model):
  
    DELETE_CHOICES = [
        (True, 'Удалено администратором'),
        (False, '')
    ]

    username = models.CharField(max_length=30, verbose_name='Имя')
    content = models.TextField(verbose_name='Текст')
    delete_status = models.BooleanField(default=False, choices=DELETE_CHOICES,
                                         verbose_name='Статус')

    new = models.ForeignKey('News', on_delete=models.CASCADE, null=True,
                            related_name='news', verbose_name='Новость')
    # один пользователь ко многим комментариям:
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                            related_name='user', verbose_name='Пользователь')

    def __str__(self):
        return f"{self.username}, {self.content[:15]}..."
    
    class Meta:
        db_table = 'Комментарии'


class News(models.Model):

    #Список тьюплов для параметра choices для групповых действий
    ACTIVITY_CHOICES = [
        (True, 'Active'),
        (False, 'Deactive')
    ]

    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #теги для фильтрации:
    tag = models.ForeignKey(Tags, on_delete=models.SET_DEFAULT, null=True, default='Другое',
                            related_name='tag', verbose_name='Тег')
    #параметр choices задаеся для групповых действий
    active = models.BooleanField(default=False, choices=ACTIVITY_CHOICES)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                                related_name='author', verbose_name='Автор')

    def __str__(self):
        #через split убираем отображение долей секунды
        return f"{self.title} | {str(self.created_at).split('.')[0]} | Активность: {self.active}"

    class Meta:
        db_table = 'Список новостей'
        #Отсортируем по дате публикации: сначала свежие.
        #для сортировки в обратном порядке указываем "-" перед параметром:
        ordering = ['-created_at']

        permissions = (
            ('can_activate', 'Can activate news'),
        )

news/newspaper/forms.py
from django import forms
from newspaper.models import News, Comments

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('title', 'content', 'tag')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('username', 'content')

news/newspaper/views.py
from re import template
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import View
from newspaper.models import Comments, News,Tags
from user_auth.models import Profile
from newspaper.forms import CommentForm, NewsForm
from django.views.generic import ListView

# Create your views here.

class NewsView(ListView):
    
    model = News
    context_object_name = 'news_list'
    template_name = 'newspaper/index.html'
    #переопределяем метод get_context_data для определения дополнительных
    #ключей context помимо news_list
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости'
        context['tags'] = Tags.objects.all()
        return context
    #переопредяем метод get_queryset для фильтрации ативных новостей
    def get_queryset(self):
        if self.request.GET.get('sorted')=='1': #проверка наличия параметра в строке для фильтрации по дате
            return News.objects.filter(active=True).order_by('created_at')
        return News.objects.filter(active=True)

#Представление для фильтрации новостей по тегам
class NewsViewTag(ListView):

    model = News
    context_object_name = 'news_list'
    template_name = 'newspaper/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости'
        context['tags'] = Tags.objects.all()
        return context
    #переопределяем метод get_queryset для выдачи новостей с выбранными тегами
    #и при этом активными
    #tag _ _ id значит что фильтруем по id связанной модели, заданной в поле tag
    def get_queryset(self):
        if self.request.GET.get('sorted')=='1':#проверка передаваемого параметра из строки ссылки
            print(self.request.GET.get('sorted'))
            return News.objects.filter(tag__id=self.kwargs['tag_id'], active=True).order_by('created_at')
        return News.objects.filter(tag__id=self.kwargs['tag_id'], active=True)


class NewsDetail(View):

    def get(self, request, news_id):

        news_data = News.objects.get(id=news_id)
        #ЧЕРЕЗ ФИЛЬТР ПОЛУЧАЕМ ВСЕ КОММЕНТЫ ДЛЯ НОВОСТИ С ПЕРЕДАВАЕМЫМ ID:
        comments = Comments.objects.filter(new_id=news_id)

        return render(request, 'newspaper/news_detail.html', context={'news_data':news_data,
                                                                     'comments':comments})



class NewsCreate(View):

    def get(self, request):

        news_form = NewsForm()

        return render(request, 'newspaper/create_news.html', context={'news_form':news_form})

    def post(self, request):

        news_form = NewsForm(request.POST)
        #добавление новости в БД
        if news_form.is_valid():
            news_form.cleaned_data['author'] = request.user
            News.objects.create(**news_form.cleaned_data)
            return HttpResponseRedirect('/newspaper/')
        
        #повышение счетчика публикованных новостей автора
        

        return render(request, 'newspaper/create_news.html', context={'news_form':news_form})



class NewsEdit(View):

    def get(self, request, news_id):
        #берем данные из БД по id
        news = News.objects.get(id = news_id)
        #вставляем в форму
        news_form = NewsForm(instance=news)

        return render(request, 'newspaper/news_edit.html', context={'news_form':news_form})

    def post(self, request, news_id):
        #берем данные из БД по id
        news = News.objects.get(id = news_id)
        #вставляем в форму по постзапросу
        news_form = NewsForm(request.POST, instance=news)
        #проверяем валидность формы
        if news_form.is_valid():
            #если форма валидна, сохранаяем данные в модель
            news.save()
            return HttpResponseRedirect('../')
        return render(request,'newspaper/news_edit.html', context={'news_form':news_form})



class CommentCreate(View):

    def get(self, request, news_id):

        comment_form = CommentForm()

        return render(request, 'newspaper/create_comment.html', context={'comment_form':comment_form})

    def post(self, request, news_id):

        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            if not request.user.is_authenticated:
                username = comment_form.cleaned_data['username']
                comment_form.cleaned_data['username'] = f"{username} (аноним)"
            comment_form.cleaned_data['new_id'] = news_id
            Comments.objects.create(**comment_form.cleaned_data)
            #редирект к комментируемой новости (просто шаг назад)
            return HttpResponseRedirect('../')
        return render(request, 'newspaper/create_comment.html', context={'comment_form':comment_form})

news/newspaper/templates/newspaper/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Создание комментария</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <form method="post" action="">
            {% csrf_token %}
            <p><label for="id_username">Имя:</label>
            <input type="text" name="username" maxlength="30" required id="id_username" value="{{request.user.username}}" readonly></p>
            <p><label for="id_content">Текст:</label> <textarea name="content" cols="40" rows="10" required id="id_content"></textarea></p>
            <button type="submit">Опубликовать комментарий</button>
        </form>
    {% else %}
        <form method="post" action="">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">Опубликовать комментарий</button>
        </form>
    {% endif %}
</body>
</html>

news/newspaper/templates/newspaper/create_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавление новости</title>
</head>
<body>
    <form method="post" action="">
        {% csrf_token %}
        {{ news_form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</body>
</html>

news/newspaper/templates/newspaper/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Новости</h1>
    <! на изначальной странице данные !>
    <! отсортированны по новизне по умолчанию !>
    <! из модели, поэтому кпопка неюзабельная !>
    <p>Сортировать по дате публикации:
    <button><a href="?sorted=0">Сначала новые</a> </button> | 
    <button><a href="?sorted=1">Сначала старые</a></button></p>
    {% if tags %}
        <p>Сортировать по тегам: <a href="/newspaper">Все</a> |
            {% for tag in tags %}
               <a href="/newspaper/tag/{{ tag.id }}/">{{ tag.title }}</a> |
            {% endfor %}
        </p>
    {% endif %}
    {% if news_list %}
        {% for news in news_list %}
            <h2><a href='news/{{ news.id }}/'>{{ news.title }}</a></h2>
            <i>(Категория: {{ news.tag }})</i>
            <p>Дата создания: {{ news.created_at }}</p>
            <p>{{ news.content }}</p>
            <p>Дата обновления: {{ news.updated_at }}</p>
        {% endfor %}
    {% else %}
        <h2>Новостей нет</h2>    
    {% endif %}
    
    <! кнопка с ссылкой при выполнении условия:!>
    <! если есть разрешение на создание новости!>
    <! то есть если ты верифицированный пользователь!>
    {% if perms.newspaper.add_news %}
    <a href='/newspaper/create/'><button>Добавить новость</button></a>
    {% endif %}
</body>
</html>

news/newspaper/templates/newspaper/news_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ news_data.title }}</title>
</head>
<body>
    <h1> {{ news_data.title }} </h1>
    <p> {{ news_data.content }} </p>
    {% if request.user == news_data.author %}
    <! кнопка с ссылкой для редактирования новости !>
        <a href='edit/'><button>Редактировать новость</button></a>
    {% endif %}
    <h3>Комментарии</h3>
    {% if comments %}
        {% for comment in comments %}
            <h4> {{ comment.username }}: </h4>
            <p> {{ comment.content }} </p>
        {% endfor %}
    {% else %}
        <p>Комментариев нет</p>
    {% endif %}
    <! кнопка с ссылкой для добавления комментария !>
    <a href='add_comment/'><button>Добавить комментрарий</button></a>
</body>
</html>

news/newspaper/templates/newspaper/news_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Редактирование новости</title>
</head>
<body>
    <form method="post" action="">
        {% csrf_token %}
        {{ news_form.as_p }}
        <button type="submit">Изменить</button>
    </form>
</body>
</html>